#!/usr/bin/env python3

try:
    # พิมพ์ข้อความ
    print("Enter a number less than 25")
    
    # (integer)
    num = int(input())

    # เช็คว่ามากกว่า 25 หรือไม่
    if num > 25:
        print("Error")
    else:
        # ใช้ while loop 
        while num <= 25:
            print("Inside the loop, my variable is " + str(num))
            num += 1  # บวกค่าเพิ่มทีละ 1

except ValueError:
    # กันพิมพ์ตัวหนังสือเข้ามาแทนตัวเลข
    pass