#!/usr/bin/env python3

try:
    # พิมพ์ข้อความให้ผู้ใช้ใส่ตัวเลข
    print("Enter a number less than 25")
    
    # รับค่าและแปลงเป็นตัวเลข (integer)
    num = int(input())

    # เช็คว่ามากกว่า 25 หรือไม่
    if num > 25:
        print("Error")
    else:
        # ใช้ while loop รันตั้งแต่เลขที่รับมา ไปจนถึง 25
        while num <= 25:
            print("Inside the loop, my variable is " + str(num))
            num += 1  # บวกค่าเพิ่มทีละ 1

except ValueError:
    # กันกรณีผู้ใช้พิมพ์ตัวหนังสือเข้ามาแทนตัวเลข
    pass