#!/usr/bin/env python3

# รับข้อความแรกจากผู้ใช้
user_input = input("What you gotta say? : ")

# ใช้ while loop เช็คว่าถ้าข้อความไม่ใช่ "STOP" ให้ทำงานต่อไป
while user_input != "STOP":
    # รับข้อความรอบถัดไป พร้อมแสดงประโยคกวนๆ
    user_input = input("I got that! Anything else? : ")