#!/usr/bin/env python3

try:
    # รับค่าและแปลงเป็นตัวเลข
    number = int(input())

    # เช็คเงื่อนไข
    if number == 0:
        print("This number is equal to zero.")
    else:
        print("This number is different from zero.")

except ValueError:
    # กัน error 
    print("This number is different from zero.")